apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rubis-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: rubis-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
