apiVersion: v1
kind: Service
metadata:
  name: rubissvc
  labels:
    app: rubis-web
spec:
  type: LoadBalancer
  externalIPs: [172.16.237.52]
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: rubis-web

