apiVersion: v1
kind: ReplicationController
metadata:
  name: rubis-db  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        node: rubis-db
    spec:
      containers:
        - resources:
            limits:
              cpu: "1"
              memory: 1024Mi
            requests:
              cpu: "1"
              memory: 1024Mi
          image: pucitcloudnet/rubis-database
          #imagePullPolicy: IfNotPresent
          #image: rubis-mysql-yehia
          #imagePullPolicy: IfNotPresent
          name: rubis-db
          ports:
            - containerPort: 3306
